{
  config,
  pkgs,
  ...
}: {
  imports = [
    ./amd-gpu.nix
    ./appimages.nix
    ./autorun.nix
    ./boot.nix
    ./displaymanager.nix
    ./distrobox.nix
    ./docker.nix
    ./flatpak.nix
    ./hwclock.nix
    ./intel-amd.nix
    ./intel-gpu.nix
    ./intel-nvidia.nix
    ./kernel.nix
    ./logitech.nix
    ./nfs.nix
    ./ntp.nix
    ./nvidia.nix
    ./packages.nix
    ./polkit.nix
    ./postgres.nix
    ./python.nix
    ./printer.nix
    ./services.nix
    ./steam.nix
    ./syncthing.nix
    ./mullvad-vpn.nix
    #./virtualbox.nix
    ./vm.nix
  ];
}
